test_server_maintains_connection_and_responds (test_stability.TestStability.test_server_maintains_connection_and_responds)
Tests if the IRC server maintains a connection and consistently responds ... ERROR

======================================================================
ERROR: test_server_maintains_connection_and_responds (test_stability.TestStability.test_server_maintains_connection_and_responds)
Tests if the IRC server maintains a connection and consistently responds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/github/ft_irc_dev/irc_tester/tests/irc_tester_utils.py", line 173, in setUp
    self.sock.connect((self.SERVER_HOST, self.SERVER_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
